"""Stage 6 - Feature engineering.

Responsible for:
- Turning raw telemetry into model inputs (e.g. rolling averages, rates of change)
- Applying the SAME transformations at training time and prediction time

Keeping this in one module prevents "training/serving skew", where the model
sees differently prepared data in production than it was trained on.
"""

import pandas as pd

# Raw telemetry columns the engineered features are built from.
RAW_FEATURE_COLUMNS = [
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]",
]

# Raw columns + engineered columns, for the feature-engineered model.
ENGINEERED_FEATURE_COLUMNS = RAW_FEATURE_COLUMNS + [
    "temperature_difference",
    "power_proxy",
    "wear_torque_interaction",
]


def add_engineered_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add reliability-style engineered features to telemetry data.

    Does not modify df in place - returns a new DataFrame, so callers can't
    be surprised by a function mutating data they still hold a reference to.

    Adds:
        temperature_difference: process temperature - air temperature.
            A proxy for heat generated by the machine doing work, rather
            than ambient conditions both raw temperatures drift with.
        power_proxy: torque * rotational speed.
            Proportional to mechanical power output - i.e. load.
        wear_torque_interaction: tool wear * torque.
            A worn tool under high torque is a worse situation than either
            wear or torque alone would suggest.

    Args:
        df: Telemetry data containing RAW_FEATURE_COLUMNS.

    Returns:
        A copy of df with the three engineered columns added.
    """
    df = df.copy()

    df["temperature_difference"] = (
        df["Process temperature [K]"] - df["Air temperature [K]"]
    )
    df["power_proxy"] = df["Rotational speed [rpm]"] * df["Torque [Nm]"]
    df["wear_torque_interaction"] = df["Tool wear [min]"] * df["Torque [Nm]"]

    return df


if __name__ == "__main__":
    from src.data_loader import load_telemetry

    data = load_telemetry()
    engineered = add_engineered_features(data)
    print(engineered[ENGINEERED_FEATURE_COLUMNS].head())
